// zenith_web/src/views/CastPlayer.vue
<template>
  <div class="root">
    <div style="flex: 1"></div>
    <div class="row-centered">
      <v-icon size="200" v-if="!connected">mdi-cast</v-icon>
      <v-icon size="200" v-else color="blue">mdi-cast-connected</v-icon>
    </div>
    <div class="row-centered" v-if="!connected">
      <div>
        <v-select
          v-if="info"
          label="Subtitles"
          :items="subtitles"
          item-text="text"
          item-value="value"
          v-model="subtitle"
          solo
        />
      </div>
    </div>
    <div class="row-centered">
      <v-btn v-if="!connected" @click="onCast">Cast</v-btn>
      <v-btn v-else @click="onDisconnect">Stop</v-btn>
    </div>
    <div style="flex: 1"></div>
    <div class="row-centered bottom-controls">
      <v-btn fab large light color="grey lighten-2">
        <v-icon v-if="connected && paused">mdi-play</v-icon>
        <v-icon v-else>mdi-pause</v-icon>
      </v-btn>
    </div>
  </div>
</template>

<style scoped>
.root {
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
}

.row-centered {
  display: flex;
  justify-content: center;
}

.bottom-controls {
  padding: 16px;
}
</style>

<script lang="ts">
import Vue from 'vue'

import api, { StreamInfo } from '@/api'
import gcast from '@/gcast'

export default Vue.extend({
  data() {
    return {
      info: null as StreamInfo | null,
      subtitle: null as number | null,
    }
  },

  computed: {
    ready() {
      return gcast.state.ready
    },

    connected() {
      return gcast.state.connected
    },

    paused() {
      return gcast.state.paused
    },

    currentTime() {
      return gcast.state.currentTime
    },

    subtitles(): { text: string; value: number }[] {
      return (
        this.info?.subtitles?.map(s => ({
          text: s.title || s.language || 'Unknown',
          value: s.index,
        })) ?? []
      )
    },
  },

  async mounted() {
    const id = this.$route.params.id
    this.info = await api.stream.getInfo(id)
  },

  methods: {
    onCast() {
      gcast.connect().then(session => {
        const id = this.$route.params.id
        const url = origin + api.stream.getTranscodeUrl(id)
        const info = new window.chrome.cast.media.MediaInfo(url, 'video/mp4')

        if (this.subtitle !== null) {
          const id = this.$route.params.id
          const type = window.chrome.cast.media.TrackType.TEXT
          const subtitle = new window.chrome.cast.media.Track(1, type)
          const item = this.info?.subtitles.find(s => s.index === this.subtitle)

          if (!item) {
            throw new Error('invalid subtitle track index')
          }

          subtitle.trackContentId =
            origin + `/api/stream/${id}/subtitles/${this.subtitle}`

          subtitle.trackContentType = 'text/vtt'
          subtitle.subtype = window.chrome.cast.media.TextTrackType.SUBTITLES
          subtitle.name = item.title || item.language || ''
          subtitle.language = item.language || ''

          info.tracks = [subtitle]
        }

        const request = new window.chrome.cast.media.LoadRequest(info)

        session.loadMedia(request).then(() => {
          if (this.subtitle !== null) {
            const media = session.getMediaSession()
            if (media) {
              media.editTracksInfo(
                new window.chrome.cast.media.EditTracksInfoRequest([1]),
                () => undefined,
                e => console.error(e),
              )
            }
          }
        })
      })
    },

    onDisconnect() {
      const context = window.cast.framework.CastContext.getInstance()
      const session = context.getCurrentSession()
      if (session) {
        session.endSession(true)
      }
    },
  },
})
</script>

// client/web/src/pages/CastPlayer.tsx
import { FC, useCallback, useEffect, useState } from "react";
import { useLocation, useParams } from "react-router";
import { css } from "@emotion/react";
import { Fab, Icon, IconButton } from "@material-ui/core";

import { useGCast } from "../gcast";
import api, { VideoInfo } from "../api";

export default function CastPlayer() {
  const params = useParams<any>();
  const query = new URLSearchParams(useLocation().search);
  const gcast = useGCast();
  const [info, setInfo] = useState<VideoInfo | null>(null);

  const subtitles = info?.subtitles || [];
  const requestedSubtitle = parseInt(query.get("subtitle") || "-1");

  useEffect(() => {
    if (params.id) {
      api.videos.getVideoInfo(params.id).then(setInfo);
    }
  }, [params]);

  const onStartCast = useCallback(() => {
    gcast.connect().then((session) => {
      const url = origin + api.videos.getVideoUrl(params.id);
      const info = new window.chrome.cast.media.MediaInfo(url, "video/mp4");

      if (requestedSubtitle !== -1) {
        const type = window.chrome.cast.media.TrackType.TEXT;
        const subtitle = new window.chrome.cast.media.Track(1, type);
        const item = subtitles.find((s) => s.index === requestedSubtitle);
        if (!item) {
          throw new Error("invalid subtitle track index");
        }
        subtitle.trackContentId =
          origin + `/api/videos/${params.id}/subtitles/${requestedSubtitle}`;
        subtitle.trackContentType = "text/vtt";
        subtitle.subtype = window.chrome.cast.media.TextTrackType.SUBTITLES;
        subtitle.name = item.title || item.language || "";
        subtitle.language = item.language || "";
        info.tracks = [subtitle];
      }

      const request = new window.chrome.cast.media.LoadRequest(info);

      session.loadMedia(request).then(() => {
        if (requestedSubtitle !== -1) {
          const media = session.getMediaSession();
          if (media) {
            media.editTracksInfo(
              new window.chrome.cast.media.EditTracksInfoRequest([1]),
              () => undefined,
              (e) => console.error(e)
            );
          }
        }
      });
    });
  }, [params, requestedSubtitle]);

  const onStopCast = useCallback(() => {
    const context = window.cast.framework.CastContext.getInstance();
    const session = context.getCurrentSession();
    if (session) {
      session.endSession(true);
    }
  }, []);

  const onPlayPause = useCallback(() => {
    const player = new cast.framework.RemotePlayer();
    const controller = new cast.framework.RemotePlayerController(player);
    controller.playOrPause();
  }, []);

  return (
    <div
      css={css`
        width: 100%;
        height: 100%;
      `}
    >
      <div
        css={css`
          width: 100%;
          height: 100%;
          display: flex;
          align-items: center;
          justify-content: center;
        `}
      >
        <CastButton
          connected={gcast.connected}
          onStart={onStartCast}
          onStop={onStopCast}
        />
      </div>
      {gcast.connected && (
        <Controls paused={gcast.paused} onPlayPause={onPlayPause} />
      )}
    </div>
  );
}

const CastButton: FC<{
  connected: boolean;
  onStart: () => void;
  onStop: () => void;
}> = ({ connected, onStart, onStop }) => (
  <IconButton
    onClick={() => {
      if (connected) {
        onStop();
      } else {
        onStart();
      }
    }}
    css={(theme) => css`
      padding: ${theme.spacing(4)};
    `}
  >
    <CastIcon connected={connected} />
  </IconButton>
);

const CastIcon: FC<{ connected: boolean }> = ({ connected }) =>
  connected ? (
    <Icon
      css={css`
        color: #2b5cff;
        font-size: 128px;
      `}
    >
      cast
    </Icon>
  ) : (
    <Icon
      css={css`
        font-size: 128px;
      `}
    >
      cast
    </Icon>
  );

const Controls: FC<{ paused: boolean; onPlayPause: () => void }> = ({
  paused,
  onPlayPause,
}) => (
  <div
    css={(theme) => css`
      position: absolute;
      width: 100%;
      bottom: 0;
      padding: ${theme.spacing(4)};
      display: flex;
      justify-content: center;
    `}
  >
    <Fab size="large" onClick={onPlayPause}>
      {paused ? <Icon>play_arrow</Icon> : <Icon>pause</Icon>}
    </Fab>
  </div>
);
