// zenith_web/src/views/Episode.vue
<template>
  <div v-if="episode">
    <v-img :src="episode.thumbnail" style="aspect-ratio: 16 / 9" />
    <div class="text-h4 mx-4 mt-6">
      {{ episode.episode_number }} - {{ episode.name }}
    </div>
    <div class="text-h6 mx-4" v-if="show">{{ show.name }}</div>
    <div class="text-caption mx-4 mb-2" v-if="season">
      {{ season.name }}
      <span class="mx-1">•</span>
      {{ duration }}
    </div>
    <div class="text-body-2 mx-4">{{ episode.overview }}</div>
    <v-btn class="my-4 ml-4 mr-1" color="accent" @click="onPlay">
      <v-icon left>mdi-play</v-icon> Play
    </v-btn>
    <v-btn class="my-4 mx-1" color="secondary" @click="onCast">
      <v-icon left>mdi-cast</v-icon> Cast
    </v-btn>
    <v-btn class="my-4 mx-1" color="secondary" @click="refreshMetadata">
      <v-icon>mdi-refresh</v-icon>
    </v-btn>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

import api, { TvEpisode, TvSeason, TvShow } from '@/api'
import gcast from '@/gcast'

export default Vue.extend({
  data() {
    return {
      show: null as TvShow | null,
      season: null as TvSeason | null,
      episode: null as TvEpisode | null,
    }
  },

  computed: {
    duration(): string | null {
      if (!this.episode) return null
      const duration = this.episode.duration
      if (duration <= 90 * 60) {
        return `${Math.floor(duration / 60)}m`
      } else {
        const hours = Math.floor(duration / 3600)
        const minutes = Math.floor((duration % 3600) / 60)
        return `${hours}h ${minutes}m`
      }
    },
  },

  async mounted() {
    this.episode = await api.tv.getEpisode(this.$route.params.id)
    api.tv.getShow(this.episode.show_id).then(show => (this.show = show))
    api.tv
      .getSeason(this.episode.season_id)
      .then(season => (this.season = season))
  },

  methods: {
    onPlay() {
      this.$router.push(`/player/${this.$route.params.id}`)
    },

    onCast() {
      gcast.connect().then(session => {
        const id = this.$route.params.id
        const url = origin + api.stream.getTranscodeUrl(id)
        const info = new window.chrome.cast.media.MediaInfo(url, 'video/mp4')
        const request = new window.chrome.cast.media.LoadRequest(info)

        session.loadMedia(request).then(() => {
          this.$router.push(`/cast/${this.$route.params.id}`)
        })
      })
    },

    refreshMetadata() {
      api.metadata.refresh(this.$route.params.id)
    },
  },
})
</script>

// client/web/src/pages/Episode.tsx
import { useEffect, useState } from "react";
import { useHistory, useParams } from "react-router";
import { css, Theme } from "@emotion/react";
import { Button, Icon, LinearProgress, Typography } from "@material-ui/core";

import api, { TvEpisode, VideoInfo } from "../api";
import MediaInfo from "../components/MediaInfo";
import SubtitleSelect from "../components/SubtitleSelect";

const styles = {
  root: css`
    height: 100%;
    overflow-y: auto;
  `,

  backdrop: css`
    width: 100%;
    aspect-ratio: 16 / 9;
  `,

  title: (theme: Theme) => css`
    margin: 0 ${theme.spacing(2)};
    margin-top: ${theme.spacing(3)};
  `,

  subtitle: (theme: Theme) => css`
    margin: 0 ${theme.spacing(2)};
  `,

  play: (theme: Theme) => css`
    margin: ${theme.spacing(2)};
  `,

  overview: (theme: Theme) =>
    css`
      margin: 0 ${theme.spacing(2)};
    `,
};

function displayDuration(duration: number) {
  if (duration <= 90 * 60) {
    return `${Math.floor(duration / 60)}m`;
  } else {
    const hours = Math.floor(duration / 3600);
    const minutes = Math.floor((duration % 3600) / 60);
    return `${hours}h ${minutes}m`;
  }
}

export default function () {
  const params = useParams<any>();
  const history = useHistory();
  const [episode, setEpisode] = useState<TvEpisode | null>(null);
  const [video, setVideo] = useState<VideoInfo | null>(null);
  const [subtitle, setSubtitle] = useState<"none" | number>("none");

  useEffect(() => {
    api.tv.getEpisode(params.id).then(setEpisode);
    api.videos.getVideoInfo(params.id).then(setVideo);
  }, []);

  if (!episode || !video) {
    return <LinearProgress variant="indeterminate" />;
  }

  function onPlay(player: "cast" | "player" = "player") {
    if (episode) {
      let url = `/${player}/${episode.id}`;

      if (subtitle !== "none") {
        url += `?subtitle=${subtitle}`;
      }

      history.push(url);
    }
  }

  return (
    <div css={styles.root}>
      <img src={episode.thumbnail!!} css={styles.backdrop} />
      <Typography variant="h4" css={styles.title}>
        {episode.name}
      </Typography>
      <Typography variant="caption" component="div" css={styles.subtitle}>
        E{episode.episode_number.toString().padStart(2, "0")} -{" "}
        {displayDuration(episode.duration)}
      </Typography>
      <Button
        variant="contained"
        startIcon={<Icon>play_arrow</Icon>}
        css={styles.play}
        onClick={() => onPlay()}
      >
        Play
      </Button>
      <Button variant="outlined" onClick={() => onPlay("cast")}>
        <Icon color="action">cast</Icon>
      </Button>
      <div
        css={(theme) => css`
          margin: 0 ${theme.spacing(2)};
          margin-bottom: ${theme.spacing(2)};
        `}
      >
        <SubtitleSelect
          subtitles={video.subtitles}
          value={subtitle}
          onChange={setSubtitle}
        />
      </div>
      <Typography variant="body2" css={styles.overview}>
        {episode.overview}
      </Typography>
      <MediaInfo info={video} />
    </div>
  );
}
