// zenith_web/src/views/Movie.vue
<template>
  <div v-if="movie" class="root">
    <div v-if="$vuetify.breakpoint.mobile">
      <v-img :src="movie.backdrop" style="aspect-ratio: 16 / 9" />
      <div class="text-h4 mx-4 mt-6">{{ movie.title }}</div>
      <div class="text-caption mx-4 mb-2">
        {{ movie.releaseYear() }} • {{ duration }}
      </div>
      <div class="text-body-2 mx-4">{{ movie.overview }}</div>
      <v-btn class="ma-4" color="accent" @click="onPlay">
        <v-icon left>mdi-play</v-icon> Play
      </v-btn>
    </div>
    <div v-else style="width: 100%; height: 100%">
      <div class="backdrop" :style="`background-image: url(${movie.backdrop})`">
        <div class="backdrop-overlay"></div>
      </div>
      <div class="content">
        <div class="main">
          <v-card max-width="260px" elevation="8">
            <v-img :src="movie.poster"></v-img>
          </v-card>
          <div class="main-content">
            <div class="text-h3">{{ movie.title }}</div>
            <div class="my-2 text-body-2">
              {{ movie.releaseYear() }} • {{ duration }}
            </div>
            <div class="my-6">{{ movie.overview }}</div>
            <v-btn color="accent" @click="onPlay">
              <v-icon left>mdi-play</v-icon> Play
            </v-btn>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.root {
  width: 100%;
  height: 100%;
}

.backdrop {
  width: 100%;
  height: 100%;
  background-position: center;
  background-size: cover;
}

.backdrop-overlay {
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.7);
}

.content {
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  overflow-y: auto;
}

.main {
  display: flex;
  max-width: 1000px;
  margin: 92px;
}

.main-content {
  margin-left: 32px;
}
</style>

<script lang="ts">
import Vue from 'vue'

import api, { Movie } from '@/api'

export default Vue.extend({
  data() {
    return {
      movie: null as Movie | null,
    }
  },

  computed: {
    duration(): string | null {
      if (!this.movie) return null
      const duration = this.movie.duration
      if (duration <= 90 * 60) {
        return `${Math.floor(duration / 60)}m`
      } else {
        const hours = Math.floor(duration / 3600)
        const minutes = Math.floor((duration % 3600) / 60)
        return `${hours}h ${minutes}m`
      }
    },
  },

  async mounted() {
    this.movie = await api.movies.getMovie(this.$route.params.id)
  },

  methods: {
    onPlay() {
      this.$router.push(`/player/${this.$route.params.id}`)
    },
  },
})
</script>

// client/web/src/pages/Movie.tsx
import { FC, useEffect, useState } from "react";
import { useHistory, useParams } from "react-router";
import { css, Theme } from "@emotion/react";
import {
  Button,
  Card,
  CardMedia,
  Icon,
  LinearProgress,
  Typography,
  useMediaQuery,
} from "@material-ui/core";

import api, { Movie } from "../api";
import { displayDuration } from "../utils";

export default function () {
  const params = useParams<any>();
  const history = useHistory();
  const mobile = useMediaQuery((theme: Theme) => theme.breakpoints.down("md"));

  const [movie, setMovie] = useState<Movie | null>(null);

  useEffect(() => {
    api.movies.getMovie(params.id).then(setMovie);
  }, []);

  if (!movie) {
    return <LinearProgress variant="indeterminate" />;
  }

  return (
    <div
      css={css`
        height: 100%;
        overflow-y: auto;
        background-size: cover;
        background-position: center;
      `}
      style={{
        backgroundImage: mobile ? undefined : `url(${movie.backdrop})`,
      }}
    >
      <div
        css={(theme) => css`
          height: 100%;
          overflow-y: auto;

          ${theme.breakpoints.up("md")} {
            padding: 10%;
            background-color: #000a;
          }
        `}
      >
        {mobile && movie.backdrop && <MobileBackdrop src={movie.backdrop} />}
        <HeaderSection
          movie={movie}
          mobile={mobile}
          onPlay={() => history.push(`/player/${movie.id}`)}
        />
        {mobile && (
          <Typography
            variant="body2"
            css={(theme) => css`
              margin: 0 ${theme.spacing(2)};
            `}
          >
            {movie.overview}
          </Typography>
        )}
      </div>
    </div>
  );
}

const MobileBackdrop: FC<{ src: string }> = ({ src }) => (
  <img
    src={src}
    css={css`
      width: 100%;
      aspect-ratio: 16 / 9;
    `}
  />
);

const HeaderSection: FC<{
  movie: Movie;
  mobile: boolean;
  onPlay: () => void;
}> = ({ movie, mobile, onPlay }) => (
  <div
    css={(theme) => css`
      display: flex;
      align-items: center;

      ${theme.breakpoints.down("md")} {
        align-items: flex-end;
        padding: ${theme.spacing(2)};
        margin-top: -80px;
      }
    `}
  >
    <Card
      css={(theme) => css`
        min-width: 150px;

        ${theme.breakpoints.up("md")} {
          min-width: 280px;
        }
      `}
    >
      <CardMedia
        image={movie.poster!!}
        css={css`
          aspect-ratio: 2/3;
        `}
      />
    </Card>
    <div
      css={(theme) => css`
        margin-left: ${theme.spacing(2)};

        ${theme.breakpoints.up("md")} {
          margin-left: ${theme.spacing(4)};
        }
      `}
    >
      <Typography
        variant={mobile ? "h5" : "h3"}
        css={(theme) => css`
          ${theme.breakpoints.down("md")} {
            font-size: 1.2rem;
          }
        `}
      >
        {movie.title}
      </Typography>
      <Typography variant={mobile ? "caption" : "h6"} component="div">
        {displayDuration(movie.video_info.duration)}
      </Typography>
      <ActionsRow onPlay={onPlay} />
      {!mobile && (
        <Typography
          variant="body2"
          css={(theme) => css`
            margin-top: ${theme.spacing(2)};
          `}
        >
          {movie.overview}
        </Typography>
      )}
    </div>
  </div>
);

const ActionsRow: FC<{ onPlay: () => void }> = ({ onPlay }) => {
  return (
    <div
      css={(theme) =>
        css`
          margin: ${theme.spacing(2)} 0;
        `
      }
    >
      <Button
        variant="contained"
        startIcon={<Icon>play_arrow</Icon>}
        onClick={onPlay}
        css={(theme) => css`
          margin-right: ${theme.spacing(1)};
        `}
      >
        Play
      </Button>
    </div>
  );
};
