// zenith_web/src/pages/Player.tsx
import { useParams } from "react-router";
import { css } from "@material-ui/styled-engine";

import api from "../api";

export default function Player() {
  const params = useParams<any>();
  return (
    <div
      css={css`
        width: 100%;
        height: 100%;
      `}
    >
      <video
        src={api.videos.getVideoUrl(params.id)}
        controls
        autoPlay
        css={css`
          width: 100%;
          height: 100%;
        `}
      />
    </div>
  );
}

// client/web/src/pages/Player.tsx
import { useParams } from "solid-app-router";
import { Component } from "solid-js";
import preferences from "../preferences";
import * as styles from "./Player.css";

export const PlayerScreen: Component = () => {
  const params = useParams();
  return (
    <div class={styles.root}>
      <video
        autoplay
        controls
        src={`${preferences.server}/api/videos/${params.id}`}
        class={styles.video}
      />
    </div>
  );
};
