// client/web/src/pages/Home.tsx
import { useEffect, useState } from "react";
import { useHistory } from "react-router";
import { css, Theme } from "@emotion/react";
import { Typography } from "@material-ui/core";

import api, { Movie, TvShow } from "../api";
import PosterMediaItem from "../components/PosterMediaItem";

const styles = {
  root: (theme: Theme) => css`
    height: 100%;
    overflow-y: auto;
    padding: ${theme.spacing(2)} 0;
  `,

  slider: (theme: Theme) => css`
    display: flex;
    overflow-x: scroll;
    margin: ${theme.spacing(2)} 0px;
    padding: 0px ${theme.spacing(1.5)};

    &::-webkit-scrollbar {
      width: 0;
      height: 0;
    }
  `,

  item: (theme: Theme) => css`
    min-width: 130px;
    padding: ${theme.spacing(0.5)};
  `,
};

export default function () {
  const history = useHistory();
  const [movies, setMovies] = useState<Movie[]>([]);
  const [shows, setShows] = useState<TvShow[]>([]);

  useEffect(() => {
    api.movies.getRecent().then(setMovies);
    api.tv.getRecentShows().then(setShows);
  }, []);

  return (
    <div css={styles.root}>
      <Typography
        variant="h5"
        css={(theme) =>
          css`
            margin: 0 ${theme.spacing(2)};
          `
        }
      >
        New Movies
      </Typography>
      <div css={styles.slider}>
        {movies.map((movie) => (
          <div key={movie.id} css={styles.item}>
            <PosterMediaItem
              poster={movie.poster || undefined}
              primary={movie.title}
              secondary={movie.releaseYear()?.toString()}
              onClick={() => history.push(`/movies/${movie.id}`)}
            />
          </div>
        ))}
      </div>
      <Typography
        variant="h5"
        css={(theme) =>
          css`
            margin: 0 ${theme.spacing(2)};
          `
        }
      >
        Updated Shows
      </Typography>
      <div css={styles.slider}>
        {shows.map((show) => (
          <div key={show.id} css={styles.item}>
            <PosterMediaItem
              poster={show.poster || undefined}
              primary={show.name}
              secondary={show.startYear()?.toString()}
              onClick={() => history.push(`/shows/${show.id}`)}
            />
          </div>
        ))}
      </div>
    </div>
  );
}

// zenith_web/src/views/Home.vue
<template>
  <v-container>
    <div class="mt-4 mt-sm-8">
      <h1 class="text-h5 my-4">Recently Added Movies</h1>
      <slide-group style="overflow-x: auto; width: 100%">
        <poster-card
          v-for="movie in movies"
          :key="movie.id"
          :poster="movie.poster"
          :primary="movie.title"
          :secondary="movie.releaseYear()"
          @click="onMovieClick(movie.id)"
          style="width: 120px; margin: 0px 4px"
        />
      </slide-group>
    </div>
    <div class="mt-8">
      <h1 class="text-h5 my-4">Recently Added TV</h1>
      <slide-group style="overflow-x: auto; width: 100%">
        <poster-card
          v-for="show in shows"
          :key="show.id"
          :poster="show.poster"
          :primary="show.name"
          :secondary="show.startYear()"
          @click="onShowClick(show.id)"
          class="group-item mx-1"
        />
      </slide-group>
    </div>
  </v-container>
</template>

<style scoped>
.group-item {
  width: 120px;
}
</style>

<script lang="ts">
import Vue from 'vue'

import api, { Movie, TvShow } from '@/api'

import PosterCard from '@/components/PosterCard.vue'
import SlideGroup from '@/components/SlideGroup.vue'

export default Vue.extend({
  components: { PosterCard, SlideGroup },

  data() {
    return {
      movies: [] as Movie[],
      shows: [] as TvShow[],
    }
  },

  async mounted() {
    this.movies = await api.movies.getRecent()
    this.shows = await api.tv.getRecentShows()
  },

  methods: {
    onMovieClick(id: number) {
      this.$router.push({ path: `/movies/${id}` })
    },

    onShowClick(id: number) {
      this.$router.push({ path: `/shows/${id}` })
    },
  },
})
</script>
