// client/web/src/pages/Season.tsx
import { useEffect, useState } from "react";
import { useHistory, useParams } from "react-router";
import { css, Theme } from "@emotion/react";
import {
  Card,
  CardActionArea,
  CardMedia,
  Icon,
  LinearProgress,
  Typography,
} from "@material-ui/core";

import api, { Episode, Season, Show } from "../api";

const styles = {
  root: css`
    height: 100%;
    overflow-y: auto;
  `,

  backdrop: css`
    width: 100%;
    aspect-ratio: 16 / 9;
  `,

  title: (theme: Theme) => css`
    margin: 0 ${theme.spacing(2)};
    margin-top: ${theme.spacing(3)};
  `,

  subtitle: (theme: Theme) => css`
    margin: 0 ${theme.spacing(2)};
  `,

  overview: (theme: Theme) =>
    css`
      margin: ${theme.spacing(2)};
    `,

  episodes: (theme: Theme) => css`
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
    padding: ${theme.spacing(1.5)};

    @media (min-width: 768px) {
      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    }
  `,

  episode: (theme: Theme) => css`
    padding: ${theme.spacing(0.5)};
  `,
};

function displayDuration(duration: number) {
  if (duration <= 90 * 60) {
    return `${Math.floor(duration / 60)}m`;
  } else {
    const hours = Math.floor(duration / 3600);
    const minutes = Math.floor((duration % 3600) / 60);
    return `${hours}h ${minutes}m`;
  }
}

export default function () {
  const params = useParams<any>();
  const history = useHistory();
  const [show, setShow] = useState<Show | null>(null);
  const [season, setSeason] = useState<Season | null>(null);
  const [episodes, setEpisodes] = useState<Episode[]>([]);

  useEffect(() => {
    api.tv.getSeason(params.id).then((season) => {
      setSeason(season);
      api.tv.getShow(season.show_id).then(setShow);
    });

    api.tv.getEpisodes(params.id).then(setEpisodes);
  }, []);

  if (!show || !season) {
    return <LinearProgress variant="indeterminate" />;
  }

  return (
    <div css={styles.root}>
      <Typography variant="h4" css={styles.title}>
        {season.name}
      </Typography>
      <Typography variant="body2" css={styles.overview}>
        {season.overview || show.overview}
      </Typography>
      <div css={styles.episodes}>
        {episodes.map((episode) => (
          <div key={episode.id} css={styles.episode}>
            <Card>
              <CardActionArea
                onClick={() => history.push(`/episodes/${episode.id}`)}
              >
                <CardMedia
                  image={episode.thumbnail || undefined}
                  css={css`
                    aspect-ratio: 16/9;
                  `}
                />
                {episode.user_data.is_watched && (
                  <div
                    css={css`
                      width: 100%;
                      height: 100%;
                      position: absolute;
                      top: 0;
                      display: flex;
                      align-items: center;
                      justify-content: center;
                      background-color: rgba(0, 0, 0, 0.5);
                    `}
                  >
                    <Icon>check</Icon>
                  </div>
                )}
              </CardActionArea>
            </Card>
            <div
              css={(theme) => css`
                padding: ${theme.spacing(2)} 0;
              `}
            >
              <Typography
                variant="subtitle2"
                css={css`
                  text-overflow: ellipsis;
                  overflow: hidden;
                  white-space: nowrap;
                  line-height: 1em;
                `}
              >
                {episode.episode_number} - {episode.name}
              </Typography>
              <Typography
                variant="caption"
                component="div"
                css={css`
                  color: darkgray;
                `}
              >
                {displayDuration(episode.video_info.duration)}
              </Typography>
              <Typography
                variant="caption"
                component="div"
                css={css`
                  line-height: 1.2em;
                  display: -webkit-box;
                  -webkit-line-clamp: 3;
                  -webkit-box-orient: vertical;
                  overflow: hidden;
                `}
              >
                {episode.overview}
              </Typography>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// zenith_web/src/views/Season.vue
<template>
  <v-container>
    <div v-if="season" class="text-h4 mt-2 mb-4">{{ season.name }}</div>
    <div class="episode-grid">
      <div v-for="episode in episodes" :key="episode.id">
        <v-card @click="onEpisodeClick(episode.id)">
          <v-img :src="episode.thumbnail" class="thumbnail"></v-img>
          <v-overlay absolute :value="episode.is_watched">
            <v-icon>mdi-check</v-icon>
          </v-overlay>
        </v-card>
        <div class="mt-2 mb-4">
          <div class="subtitle-2 text-truncate">
            {{ episode.episode_number }} - {{ episode.name }}
          </div>
          <div class="caption text--secondary">
            {{ duration(episode.duration) }}
          </div>
          <div class="caption overview">
            {{ episode.overview }}
          </div>
        </div>
      </div>
    </div>
  </v-container>
</template>

<style scoped>
.episode-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  grid-gap: 16px;
}

.thumbnail {
  aspect-ratio: 16 / 9;
}

.overview {
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3;
  overflow: hidden;
}
</style>

<script lang="ts">
import Vue from 'vue'
export default Vue.extend({
  data() {
    return {
      season: null,
      episodes: [],
    }
  },

  async mounted() {
    const season = await fetch(
      `/api/tv/seasons/${this.$route.params.id}`,
    ).then(res => res.json())

    this.season = season

    const episodes = await fetch(
      `/api/tv/seasons/${this.$route.params.id}/episodes`,
    ).then(res => res.json())

    this.episodes = episodes
  },

  methods: {
    duration(duration: number): string {
      if (duration <= 90 * 60) {
        return `${Math.floor(duration / 60)}m`
      } else {
        const hours = Math.floor(duration / 3600)
        const minutes = Math.floor((duration % 3600) / 60)
        return `${hours}h ${minutes}m`
      }
    },

    onEpisodeClick(id: number) {
      this.$router.push({ path: `/episodes/${id}` })
    },
  },
})
</script>
