// client/web/src/pages/Show.tsx
import { useEffect, useState } from "react";
import { useHistory, useParams } from "react-router";
import { css, Theme } from "@emotion/react";
import { LinearProgress, Typography } from "@material-ui/core";

import api, { TvSeason, TvShow } from "../api";
import PosterMediaItem from "../components/PosterMediaItem";

const styles = {
  root: css`
    height: 100%;
    overflow-y: auto;
  `,

  backdrop: css`
    width: 100%;
    aspect-ratio: 16 / 9;
  `,

  title: (theme: Theme) => css`
    margin: 0 ${theme.spacing(2)};
    margin-top: ${theme.spacing(3)};
  `,

  subtitle: (theme: Theme) => css`
    margin: 0 ${theme.spacing(2)};
  `,

  overview: (theme: Theme) =>
    css`
      margin: 0 ${theme.spacing(2)};
    `,

  seasons: (theme: Theme) => css`
    display: flex;
    overflow-x: scroll;
    margin: ${theme.spacing(2)} 0px;
    padding: 0px ${theme.spacing(1.5)};

    &::-webkit-scrollbar {
      width: 0;
      height: 0;
    }
  `,

  season: (theme: Theme) => css`
    min-width: 130px;
    padding: ${theme.spacing(0.5)};
  `,
};

export default function () {
  const params = useParams<any>();
  const history = useHistory();
  const [show, setShow] = useState<TvShow | null>(null);
  const [seasons, setSeasons] = useState<TvSeason[]>([]);

  useEffect(() => {
    api.tv.getShow(params.id).then(setShow);
    api.tv.getSeasons(params.id).then(setSeasons);
  }, []);

  if (!show) {
    return <LinearProgress variant="indeterminate" />;
  }

  return (
    <div css={styles.root}>
      <img src={show.backdrop!!} css={styles.backdrop} />
      <Typography variant="h4" css={styles.title}>
        {show.name}
      </Typography>
      <Typography variant="caption" component="div" css={styles.subtitle}>
        {show.startYear()}
      </Typography>
      <Typography variant="body2" css={styles.overview}>
        {show.overview}
      </Typography>
      <div css={styles.seasons}>
        {seasons.map((season) => (
          <div key={season.id} css={styles.season}>
            <PosterMediaItem
              poster={season.poster || undefined}
              primary={season.name || ""}
              secondary={show.name}
              onClick={() => history.push(`/seasons/${season.id}`)}
            />
          </div>
        ))}
      </div>
    </div>
  );
}

// zenith_web/src/views/Show.vue
<template>
  <div v-if="show">
    <v-img :src="show.backdrop" style="aspect-ratio: 16 / 9" />
    <div class="text-h4 mx-4 mt-6 mb-2">{{ show.name }}</div>
    <div class="text-body-2 mx-4">{{ show.overview }}</div>
    <div class="mt-6">
      <div class="text-h5 mx-4">Seasons</div>
      <slide-group padding="0px 12px" style="overflow-x: auto; width: 100%">
        <poster-card
          v-for="season in seasons"
          :key="season.id"
          :poster="season.poster"
          :primary="show.name"
          :secondary="season.name"
          @click="onSeasonClick(season.id)"
          style="width: 120px; margin: 0px 4px"
        />
      </slide-group>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

import api, { TvShow } from '@/api'

import PosterCard from '@/components/PosterCard.vue'
import SlideGroup from '@/components/SlideGroup.vue'

export default Vue.extend({
  components: { PosterCard, SlideGroup },

  data() {
    return {
      show: null as TvShow | null,
      seasons: [],
    }
  },

  async mounted() {
    this.show = await api.tv.getShow(this.$route.params.id)

    const seasons = await fetch(
      `/api/tv/shows/${this.$route.params.id}/seasons`,
    ).then(res => res.json())

    this.seasons = seasons
  },

  methods: {
    onSeasonClick(id: number) {
      this.$router.push({ path: `/seasons/${id}` })
    },
  },
})
</script>

<style scoped>
.episode-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  grid-gap: 16px;
}

.thumbnail {
  aspect-ratio: 16 / 9;
}
</style>
