// zenith_web/src/views/Player.vue
<template>
  <div
    class="root"
    @mousemove="onInteraction"
    @touchmove="onInteraction"
    @click="onInteraction"
  >
    <video ref="video" class="video"></video>
    <div class="overlay" :style="{ display: showControls ? 'block' : 'none' }">
      <player-controls
        :duration="duration"
        :position="offset + position"
        :state="state"
        @pause="video.pause()"
        @play="video.play()"
        @rewind="seekTo(offset + position - $event)"
        @fast-forward="seekTo(offset + position + $event)"
        @seek-start="startSeek"
        @seek-end="seekTo($event)"
        @toggle-fullscreen="toggleFullscreen"
      />
    </div>
  </div>
</template>

<style scoped>
.root {
  width: 100%;
  height: 100%;
}

.video {
  position: absolute;
  width: 100%;
  height: 100%;
  top: 0;
  background-color: black;
}

.overlay {
  position: absolute;
  width: 100%;
  height: 100%;
  top: 0;
}
</style>

<script lang="ts">
import Vue from 'vue'

import api from '@/api'
import fullscreen from '@/fullscreen'

import PlayerControls from '@/components/PlayerControls.vue'

export default Vue.extend({
  components: { PlayerControls },

  data() {
    return {
      state: 'playing',
      duration: 0,
      offset: 0,
      position: 0,
      interval: undefined as number | undefined,
      controls: true,
      timeout: undefined as number | undefined,
    }
  },

  computed: {
    id() {
      return this.$route.params.id
    },
    video() {
      return this.$refs.video as HTMLVideoElement
    },
    showControls(): boolean {
      return this.controls || this.state === 'paused'
    },
  },

  async mounted() {
    const info = await api.getStreamInfo(this.$route.params.id)

    this.duration = info.duration

    this.interval = window.setInterval(() => {
      this.position = this.video.currentTime
    }, 200)

    this.video.addEventListener('pause', () => {
      this.state = 'paused'
    })

    this.video.addEventListener('play', () => {
      this.state = 'playing'
    })

    this.seekTo(0)
    this.delayedHideControls()
  },

  beforeDestroy() {
    if (this.interval) {
      window.clearInterval(this.interval)
    }
  },

  methods: {
    startSeek() {
      this.video.pause()
    },

    seekTo(position: number) {
      this.offset = Math.floor(Math.min(this.duration, Math.max(0, position)))
      this.position = 0
      this.video.src = api.getTranscodeStreamUrl(this.id, this.offset)
      this.video.play()
    },

    delayedHideControls() {
      if (this.timeout) window.clearTimeout(this.timeout)
      this.timeout = window.setTimeout(() => (this.controls = false), 3000)
    },

    toggleFullscreen() {
      fullscreen.toggle()
    },

    onInteraction() {
      this.controls = true
      this.delayedHideControls()
    },
  },
})
</script>

// zenith_web/src/pages/Player.tsx
import { useEffect, useRef } from "react";
import { useParams } from "react-router";
import styled from "styled-components";

interface StreamInfo {
  path: string;
  duration: number;
}

async function getStreamInfo(id: any): Promise<StreamInfo> {
  const res = await fetch("/api/stream/" + id + "/info");
  const data = await res.json();
  return data;
}

export class VideoPlayer {
  private interval: any;

  private video: HTMLVideoElement;
  private source: HTMLSourceElement;
  private seekbar: HTMLInputElement;

  private seeking = false;
  private disabled = false;
  private startTime = 0;
  private streamId: number | string | null = null;

  constructor(private readonly container: HTMLDivElement) {
    this.container.style.position = "relative";

    this.video = document.createElement("video");
    this.source = document.createElement("source");

    this.video.style.width = "100%";
    this.video.style.height = "100%";
    this.video.style.objectFit = "contain";
    this.video.style.background = "black";

    const overlay = document.createElement("div");

    overlay.style.position = "absolute";
    overlay.style.width = "100%";
    overlay.style.height = "100%";
    overlay.style.top = "0";

    const controls = document.createElement("div");
    const seekbar = document.createElement("input");

    seekbar.type = "range";
    seekbar.min = "0";
    seekbar.value = "0";
    seekbar.style.width = "100%";
    seekbar.style.margin = "0";

    this.seekbar = seekbar;

    overlay.appendChild(controls);
    controls.appendChild(seekbar);

    this.container.appendChild(this.video);
    this.container.appendChild(overlay);
    this.video.appendChild(this.source);

    this.interval = window.setInterval(() => {
      if (!this.video.paused && !this.seeking) {
        const currentTime = this.startTime + this.video.currentTime;
        this.seekbar.value = currentTime.toString();
      }
    }, 100);

    this.seekbar.addEventListener("mousedown", () => {
      if (!this.disabled) {
        this.video.pause();
      }
    });

    this.seekbar.addEventListener("mouseup", () => {
      if (this.streamId != null && !this.disabled) {
        this.seeking = true;
        this.disabled = true;
        this.startTime = parseFloat(this.seekbar.value);
        this.source.src =
          "/api/stream/" + this.streamId + "?start=" + this.startTime;
        this.video.load();
        this.video.play().then(() => {
          this.disabled = false;
          this.seeking = false;
        });
      }
    });
  }

  public async setStreamId(id: string | number) {
    const info = await getStreamInfo(id);

    this.startTime = 0;
    this.streamId = id;

    this.seekbar.max = info.duration.toString();
    this.source.src = "/api/stream/" + id + "?start=" + this.startTime;

    this.video.load();
    this.video.play();
  }

  public destroy() {
    window.clearInterval(this.interval);
    this.container.innerHTML = "";
  }
}

export function Player() {
  const params = useParams<{ id: string }>();
  const video = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (video.current) {
      const player = new VideoPlayer(video.current);
      player.setStreamId(params.id);
      return () => player.destroy();
    }
  }, [params, video]);

  return <VideoContainer ref={video}></VideoContainer>;
}

const VideoContainer = styled.figure`
  margin: 0;
  width: 100vw;
  height: 100vh;
  position: relative;
`;
